#!/bin/bash

# set the working directory to blinkies image folder
cd "$HOME/Documents/neocities/public/about/images/blinkies/"

# get the json file with the names of the blinkies
aboutJson="$HOME/Documents/neocities/eleventy/about/about.json"

# loop through the animated blinkies
shopt -s nocaseglob
shopt -s nullglob
for i in *.{gif,webp,avif}; do

    # get the name of the file without the extension
    name="${i%.*}"
    
    # if there's no png version, convert
    if [ ! -f "$name.png" ]; then
        echo "converting $i"
        mogrify -format png "$i""[0]"
    fi
done

# replace the blinkies array in aboutJson with array of non-png files in the blinkies directory
jq --argjson arr "$(find . -maxdepth 1 -type f ! -iname '*.png' -printf '%f\n' | jq -R . | jq -s .)" '.blinkies = $arr' "$aboutJson" > "$aboutJson.tmp" && mv "$aboutJson.tmp" "$aboutJson"

# set the working directory to stamps image folder
cd "$HOME/Documents/neocities/public/about/images/stamps"

# get the names of the stamps without the extension
find . -maxdepth 1 -type f -printf '%f\n' | sed 's/\(.*\)\..*/\1/g' | sort > /tmp/stamps.txt

# for every line in /tmp/stamps.txt, check if it's in the aboutJson.stamps array
while read -r line; do
    if ! jq -r '.stamps[]' "$aboutJson" | grep -q "$line"; then
        
        # print the stamps that are in the stamp folder but not in the stamp array
        echo "$line"
    fi
done < "/tmp/stamps.txt"

# to do: add the missing stamps to aboutJson.stamps array

# remove temporary stamp list
rm "/tmp/stamps.txt"