#!/bin/bash

eleventy="$HOME/Documents/neocities/eleventy"
public="$HOME/Documents/neocities/public"

# build eleventy folder and copy to relevant public folder
eleventy_to_neocities() {
  page=$1
  index=$2
  cd $eleventy

  # if .eleventy.$page.js exists, use it
  if [ -f ".eleventy.$page.js" ]; then
    npx @11ty/eleventy --config=.eleventy.$page.js
  else
    npx @11ty/eleventy --input=neocities/$page --output=_site/$page
  fi

  rsync -avhn _site/$page/ ../public/$page --exclude="*.css" --exclude="*.js" --exclude="**/*.css" --exclude="**/*.js"
  echo "does this look good? (y/n)"
  read answer
  if [ $answer == "y" ]; then
    echo "copying to public folder"
    rsync -avh _site/$page/ ../public/$page --exclude="*.css" --exclude="*.js" --exclude="**/*.css" --exclude="**/*.js"
  fi
}

# copy css from public folder, needed to make cache busting function work
copy_assets() {
  if [ -f $public/$1/$1.min.css ]; then
    cp $public/$1/$1.min.css $eleventy/neocities/$1/
  else
    cp $public/$1/$2 $eleventy/neocities/$1/$2
  fi
}

# case based on first argument
case "$1" in
"about")
  echo "building about page"
  $HOME/Documents/neocities/scripts/about_image_update
  # copy_assets "about"
  eleventy_to_neocities "about" "true"
  ;;
"articles")
  echo "building articles page"
  eleventy_to_neocities "articles" "true"
  ;;
"atom")
  echo "building main atom feed"
  $HOME/Documents/neocities/scripts/obsidian_to_atom
  ;;
"changelog")
  echo "building changelog"
  eleventy_to_neocities "changelog" "true"
  ;;
"codes")
  echo "building codes folder"
  eleventy_to_neocities "codes" "false"
  ;;
"crafts")
  echo "building craft page"
  # copy_assets "crafts"
  eleventy_to_neocities "crafts" "true"
  ;;
"language")
  # copy_assets "language"
  echo "building language page"
  eleventy_to_neocities "language" "true"
  ;;
"main")
  # copy_assets "main" "css/body.min.css"
  echo "building main site"
  eleventy_to_neocities "main" "false"
  ;;
"places")
  echo "building places page"
  eleventy_to_neocities "places" "true"
  ;;
"resources")
  # copy_assets "resources"
  echo "building resources site"
  eleventy_to_neocities "resources" "false"
  ;;
"room")
  # copy_assets "room" "stuff.min.css"
  echo "building my things page"
  eleventy_to_neocities "room" "true" "my-things"
  ;;
"vegan")
  # copy_assets "vegan"
  echo "building vegan page"
  eleventy_to_neocities "vegan" "true"
  ;;
"yakuza")
  echo "building yakuza page"
  eleventy_to_neocities "yakuza" "false"
  ;;
"notebook")
  echo "building notebook"
  cd $HOME/Documents/neocities/quartz/
  npx quartz build
  cp -a public/. ../public/notes/
  ;;
"microblog")
  # ask user if they want to build today's post from obsidian
  echo "do you want to build today's post from obsidian? (y/n)"
  read answer
  if [ $answer == "y" ]; then
    echo "building $(date '+%Y-%m-%d').md"
    $HOME/Documents/neocities/scripts/obsidian_to_microblog
  fi
  echo "do you want to build the microblog? (y/n)"
  read answer
  if [ $answer == "y" ]; then
    echo "running microblog.py"
    cd $HOME/Documents/neocities/microblog
    pipenv run python microblog.py ./template.tpl ./content.txt >$HOME/Documents/neocities/public/microblog/index.html
    # mv tags ../public/microblog
    # mv pages ../public/microblog
    rsync -avhn tags ../public/microblog && rsync -avhn pages ../public/microblog
    echo "does this look good? (y/n)"
    read answer
    if [ $answer == "y" ]; then
      echo "copying to public folder"
      rsync -avh tags ../public/microblog && rsync -avh pages ../public/microblog
    fi
  fi
  ;;
*)
  echo "not a page"
  ;;
esac

# if previous command was successful
if [ $? -eq 0 ]; then

  # ask user if they want to serve site
  echo "do you want to preview the site? (y/n)"
  read answer
  if [ $answer == "y" ]; then
    npx http-server $HOME/Documents/neocities/public
  fi
fi
